Bouteloua_dactyloides_text = '''
Bouteloua dactyloides, commonly known as buffalograss or buffalo grass, is a North American prairie grass native to Canada, Mexico, and the United States. It is a shortgrass found mainly on the High Plains and is co-dominant with blue grama (B. gracilis) over most of the shortgrass prairie.[3]

Buffalo grass in North America is not the same species of grass commonly known as "buffalo" in Australia. It should not be confused with Stenotaphrum secundatum varieties such as 'Sir Walter' or 'Palmetto'.
Buffalograss is a warm-season perennial shortgrass. It is drought-, heat-, and cold-resistant. Foliage is usually 5–13 cm (2.0–5.1 in) high, though in the southern Great Plains, foliage may reach 30 cm (12 in). Buffalograss is usually dioecious, but sometimes monoecious or with perfect flowers. Flower stalks are 10–20 cm (3.9–7.9 in) tall. The male inflorescence is a panicle; the female inflorescence consists of short spikelets borne in burlike clusters, usually with two to four spikelets per bur.

Buffalograss sends out numerous, branching stolons; occasionally, it also produces rhizomes. Roots are also numerous and thoroughly occupy the soil. The numerous stolons and roots form a dense sod. Buffalograss roots are finer than those of most plains grasses, being less than 1 mm (0.039 in) in diameter.
Buffalograss is common and widespread across most of the Great Plains and in scattered locations in neighboring regions, from the Canadian Prairie Provinces to central Mexico, as well as the Mississippi Valley and the Intermountain Region.[3][4]

In Australia B. dactyloides is not called buffalograss, but is referred to as 'prairie grass'.
Bouteloua dactyloides was initially placed by Thomas Nuttall in the genus Sesleria.[1] It was later moved to the monotypic genus Buchloe.[5] In 1999, James Travis Columbus moved buffalograss to Bouteloua, which also contains the grama grasses.
Buffalograss is used as a drought-tolerant turfgrass in North America and is also grown for forage. Turfgrass cultivars include '609', 'Prairie', 'Stampede', and 'Density', while 'Comanche' and 'Texoka' are intended for forage.[6] In addition, researchers at the University of California Riverside and University of California Davis have hybridized a buffalograss cultivar, 'UC Verde',[7] creating a thick, green, drought-tolerant lawn for California's hot, dry summers.
'''