Cercis_canadensis_text = '''
Cercis canadensis, the eastern redbud, is a large deciduous shrub or small tree, native to eastern North America from southern Ontario, south to northern Florida but which can thrive as far west as California. It is the state tree of Oklahoma.
The eastern redbud typically grows to 6–9 m (20–30 ft) tall with an 8–10 m (26–33 ft) spread. It generally has a short, often twisted trunk and spreading branches. A 10-year-old tree will generally be around 5 m (16 ft) tall. The bark is dark in color, smooth, later scaly with ridges somewhat apparent, sometimes with maroon patches. The twigs are slender and zigzag, nearly black in color, spotted with lighter lenticels. The winter buds are tiny, rounded and dark red to chestnut in color. The leaves are alternate, simple, and heart shaped with an entire margin, 7–12 cm (3–4.5 in) long and wide, thin and papery, and may be slightly hairy below.
The flowers are showy, light to dark magenta pink in color, 1.5 cm (1⁄2 in) long, appearing in clusters from Spring to early Summer, on bare stems before the leaves, sometimes on the trunk itself. The flowers are pollinated by long-tongued bees such as blueberry bees and carpenter bees. Short-tongued bees apparently cannot reach the nectaries. The fruit are flattened, dry, brown, pea-like pods, 5–10 cm (2–4 in) long that contain flat, elliptical, brown seeds 6 mm (1⁄4 in) long, maturing in August to October.
In some parts of southern Appalachia, green twigs from the eastern redbud are used as seasoning for wild game such as venison and opossum. Because of this, in these mountain areas the eastern redbud is sometimes known as the spicewood tree.

In the wild, eastern redbud is a frequent native understory tree in mixed forests and hedgerows. It is also much planted as a landscape ornamental plant. The leaves are eaten by the caterpillars of some Lepidoptera, for example Henry's Elfin, the Redbud Leaffolder, the white flannel moth, the American dagger moth, the grape leaffolder, and the Io moth (Automeris io).
In the United States, this tree is difficult to grow farther west into arid areas west of western Kansas and Colorado, as there is not sufficient annual precipitation. Its far northern range of growth is the lower Midwest, Ohio Valley, to the south of Boston. There has been success with growing the tree in Columbus, Wisconsin, which has become known as the "Columbus Strain" and a seed source for nurseries.

Bark: Red brown, with deep fissures and scaly surface. Branchlets at first lustrous brown, later become darker.
Wood: Dark reddish brown; heavy, hard, coarse-grained, not strong. Sp. gr., 0.6363; weight of cu. ft. 39.65 lbs.
Winter buds: Chestnut brown, obtuse, one-eighth inch long.
Leaves: Alternate, simple, heart-shaped or broadly ovate, two to five inches long, five to seven-nerved, cordate or truncate at the base, entire, acute. They come out of the bud folded along the line of the midrib, tawny green; when they are full grown they become smooth, dark green above, paler beneath. In autumn they turn bright clear yellow. Petioles slender, terete, enlarged at the base. Stipules caducous.
Flowers: April, May, before and with the leaves, papilionaceous. Perfect, rose color, borne four to eight together, in fascicles which appear at the axils of the leaves or along the branch and sometimes on the trunk itself.
Calyx: Dark red, campanulate, oblique, five-toothed, imbricate in bud.
Corolla: Papilionaceous, petals five, nearly equal, pink or rose color, upper petal the smallest, enclosed in the bud by the wings, and encircled by the broader keel petals.
Stamens: Ten, inserted in two rows on a thin disk, free, the inner row rather shorter than the others.
Pistil: Ovary superior, inserted obliquely in the bottom of the calyx tube, stipitate; style fleshy, incurved, tipped with an obtuse stigma.
Fruit: Legume, slightly stipitate, unequally oblong, acute at each end. Compressed, tipped with the remnants of the style, straight on upper and curved on the lower edge. Two and a half to three inches long, rose color, full grown by midsummer, falls in early winter. Seeds ten to twelve, chestnut brown, one-fourth of an inch long -can be made to germinate by first dipping in boiled (99C) water (very hot) for a minute and then sowing in a pot (do not boil the seeds); cotyledons oval, flat.
C. canadensis is grown in parks and gardens, with several cultivars being available. The cultivars 'Forest Pansy'[3] and 'Ruby Falls'[4] have gained the Royal Horticultural Society's Award of Garden Merit (confirmed 2017).
'''