Bouteloua_dactyloides_text = '''
Bouteloua dactyloides, commonly known as buffalograss or buffalo grass, is a North American prairie grass native to Canada, Mexico, and the United States. It is a shortgrass found mainly on the High Plains and is co-dominant with blue grama (B. gracilis) over most of the shortgrass prairie.[3]

Buffalo grass in North America is not the same species of grass commonly known as "buffalo" in Australia. It should not be confused with Stenotaphrum secundatum varieties such as 'Sir Walter' or 'Palmetto'.
Buffalograss is a warm-season perennial shortgrass. It is drought-, heat-, and cold-resistant. Foliage is usually 5 – 13 cm  (2.0 – 5.1 in) high, though in the southern Great Plains, foliage may reach 30 cm (12 in). Buffalograss is usually dioecious, but sometimes monoecious or with perfect flowers. Flower stalks are 10–20 cm (3.9–7.9 in) tall. The male inflorescence is a panicle; the female inflorescence consists of short spikelets borne in burlike clusters, usually with two to four spikelets per bur.

Buffalograss sends out numerous, branching stolons; occasionally, it also produces rhizomes. Roots are also numerous and thoroughly occupy the soil. The numerous stolons and roots form a dense sod. Buffalograss roots are finer than those of most plains grasses, being less than 1 mm (0.039 in) in diameter.
Buffalograss is common and widespread across most of the Great Plains and in scattered locations in neighboring regions, from the Canadian Prairie Provinces to central Mexico, as well as the Mississippi Valley and the Intermountain Region.[3][4]

In Australia B. dactyloides is not called buffalograss, but is referred to as 'prairie grass'.
Bouteloua dactyloides was initially placed by Thomas Nuttall in the genus Sesleria.[1] It was later moved to the monotypic genus Buchloe.[5] In 1999, James Travis Columbus moved buffalograss to Bouteloua, which also contains the grama grasses.
Buffalograss is used as a drought-tolerant turfgrass in North America and is also grown for forage. Turfgrass cultivars include '609', 'Prairie', 'Stampede', and 'Density', while 'Comanche' and 'Texoka' are intended for forage.[6] In addition, researchers at the University of California Riverside and University of California Davis have hybridized a buffalograss cultivar, 'UC Verde',[7] creating a thick, green, drought-tolerant lawn for California's hot, dry summers.
'''

Acer_palmatum_text = '''Acer palmatum, commonly known as red emperor maple, palmate maple,[3] Japanese maple[4] or smooth Japanese-maple, is a species of woody plant native to Japan, Korea, China, eastern Mongolia, and southeast Russia.[6] Many different cultivars of this maple have been selected and they are grown worldwide for their large variety of attractive forms, leaf shapes, and spectacular colors
Acer palmatum is a deciduous shrub or small tree reaching heights of 6 to 10 m (20 to 33 ft), rarely 16 metres (52 ft), often growing as an understory plant in shady woodlands. It may have multiple trunks joining close to the ground. In habit, its canopy often takes on a dome-like form, especially when mature.[8] The leaves are 4–12 cm (1 1⁄2–4 3⁄4 in) long and wide, palmately lobed with five, seven, or nine acutely pointed lobes. The flowers are produced in small cymes, the individual flowers with five red or purple sepals and five whitish petals. The fruit is a pair of winged samaras, each samara 2–3 cm (3⁄4–1 1⁄4 in) long with a 6–8 mm (1⁄4–5⁄16 in) seed. The seeds of Acer palmatum and similar species require stratification in order to germinate.[8][9]

Even in nature, Acer palmatum displays considerable genetic variation, with seedlings from the same parent tree typically showing differences in such traits as leaf size, shape, and color. Overall form of the tree can vary from upright to weeping.[8]

Three subspecies are recognised:[8][9]

Acer palmatum subsp. palmatum. Leaves small, 4–7 cm (1 1⁄2–2 3⁄4 in) wide, with five or seven lobes and double-serrate margins; seed wings 10–15 mm (3⁄8–5⁄8 in). Lower altitudes throughout central and southern Japan (not Hokkaido).
Acer palmatum subsp. amoenum (Carrière) H.Hara. Leaves larger, 6–12 cm (2 1⁄4–4 3⁄4 in) wide, with seven or nine lobes and single-serrate margins; seed wings 20–25 mm (3⁄4–1 in). Higher altitudes throughout Japan and South Korea.
Acer palmatum subsp. matsumurae Koidz. Leaves larger, 6–12 cm (2 1⁄4–4 3⁄4 in) wide, with seven (rarely five or nine) lobes and double-serrate margins; seed wings 15–25 mm (5⁄8–1 in). Higher altitudes throughout Japan.

Acer palmatum has been cultivated in Japan for centuries and in temperate areas around the world since the 1800s.[8] The first specimen of the tree reached Britain in 1820.

When Swedish doctor-botanist Carl Peter Thunberg traveled in Japan late in the eighteenth century, he secreted out drawings of a small tree that would eventually become synonymous with the high art of oriental gardens.[10] He gave it the species name palmatum after the hand-like shape of its leaves, similar to the centuries-old Japanese names kaede and momiji, references to the 'hands' of frogs[11] and babies,[citation needed] respectively.

Japanese horticulturalists have long developed cultivars from maples found in Japan and nearby Korea and China. They are a popular choice for bonsai[12] enthusiasts and have long been a subject in art.

Numerous cultivars are popular in Europe and North America, with red-leafed favored, followed by cascading green shrubs with deeply dissected leaves.[8]

Preparations from the branches and leaves are used as a treatment in traditional Chinese medicine.
Acer palmatum includes hundreds of named cultivars with a variety forms, colors, leaf types, sizes, and preferred growing conditions. Heights of mature specimens range from 0.5 to 25 m (1 1⁄2 to 82 ft), depending on type. Some tolerate sun, but most prefer part shade, especially in hotter climates. Almost all are adaptable and blend well with companion plants. The trees are particularly suitable for borders and ornamental paths because the root systems are compact and not invasive. Many varieties of Acer palmatum are successfully grown in containers.[14] Trees are prone to die during periods of drought and prefer consistent water conditions; more established trees are less prone to drought. Trees should be mulched with a thick layer of bark. Well-drained soil is essential as they will not survive in soggy waterlogged soil. Trees do not require or appreciate heavy fertilization and should only be lightly fertilized, preferably using slow-release fertilizer with a 3 to 1 ratio of nitrogen to phosphorus respectively. Nitrogen lawn fertilizer should be avoided in the immediate vicinity of these trees as excessive nitrogen can cause overly vigorous growth that is prone to pathogens.
If space is not a constraint, no pruning is necessary except to remove any dead branches. Trees naturally self-prune foliage that doesn't receive enough light, such as internal branches which are overly shaded by its own canopy. Some growers prefer to shape their trees artistically or to thin out interior branches to better expose the graceful main branches. The form of the tree, especially without leaves in winter, can be of great interest and can be pruned to highlight this feature. Trees heal readily after pruning without needing aftercare. This species should not be pruned like a hedge, but instead methodically shaped by carefully choosing individual branches to remove. They can also be pruned just to maintain a smaller size to suit a particular location. Acer palmatum can also be used as espalier
Over 1,000 cultivars have been chosen for particular characteristics, which are propagated by asexual reproduction most often by grafting, but some cultivars can also be propagated by budding, cuttings, tissue culture, or layering. Some cultivars are not in cultivation in the Western world or have been lost over the generations, but many new cultivars are developed each decade.[8] Cultivars are chosen for phenotypical aspects such as leaf shape and size (shallowly to deeply lobed, some also palmately compound), leaf color (ranging from chartreuse through dark green or from red to dark purple, others variegated with various patterns of white and pink), bark texture and color, and growth pattern. Most cultivars are less vigorous and smaller than is typical for the species, but are more interesting than the relatively mundane species. Cultivars come in a large variety of forms including upright, broom, weeping, cascading, dwarf, and shrub. Most cultivars are artificially selected from seedlings of open-pollinated plants, purposeful breeding is not common, and less often from grafts of witch's brooms.
In Japan, iromomiji is used as an accent tree in Japanese gardens, providing gentle shade next to the house in the summer and beautiful colors in autumn. Many cultivars have characteristics that come into prominence during different seasons, including the color of new or mature leaves, extraordinary autumn color, color and shape of samaras, or even bark that becomes more brightly colored during the winter. Some cultivars can scarcely be distinguished from others unless labeled. In some cases, identical cultivars go by different names, while in other cases, different cultivars may be given the same name.

'''