Magnolia_soulangeana_text = ''''
Magnolia × soulangeana (saucer magnolia) is a hybrid plant in the genus Magnolia and family Magnoliaceae. It is a deciduous tree with large, early-blooming flowers in various shades of white, pink, and purple. It is one of the most commonly used magnolias in horticulture, being widely planted in the British Isles, especially in the south of England; and in the United States, especially the east and west coasts.
Magnolia × soulangeana was initially bred by French plantsman Étienne Soulange-Bodin (1774–1846), a retired cavalry officer in Napoleon's army, at his château de Fromont near Paris. He crossed Magnolia denudata with M. liliiflora in 1820, and was impressed with the resulting progeny's first precocious flowering in 1826.[3][4]

From France, the hybrid quickly entered cultivation in England and other parts of Europe, and also North America. Since then, plant breeders in many countries have continued to develop this magnolia, and over a hundred named horticultural varieties (cultivars) are now known.
Growing as a multistemmed large shrub or small tree, Magnolia × soulangeana has alternate, simple, shiny, dark green oval-shaped leaves on stout stems. Its flowers emerge dramatically on a bare tree in early spring, with the deciduous leaves expanding shortly thereafter, lasting through summer until autumn.[2]

Magnolia × soulangeana flowers are large, commonly 10–20 cm (4–8 in) across, and colored various shades of white, pink, and maroon. An American variety, 'Grace McDade' from Alabama, is reported to bear the largest flowers, with a 35 cm (14 in) diameter, white tinged with pinkish-purple.[2] Another variety, Magnolia × soulangeana 'Jurmag1', is supposed to have the darkest and tightest flowers. The exact timing and length of flowering varies between named varieties, as does the shape of the flower. Some are globular, others a cup-and-saucer shape.
Magnolia × soulangeana is notable for its ease of cultivation, and its relative tolerance to wind and alkaline soils (two vulnerabilities of many other magnolias). The cultivar 'Brozzonii' has gained the Royal Horticultural Society's Award of Garden Merit.
'''