Nerium_text = '''
Nerium oleander /ˈnɪəriəm ˈoʊliːændər/[3] is a shrub or small tree in the dogbane family Apocynaceae, toxic in all its parts. It is the only species currently classified in the genus Nerium. It is most commonly known as nerium[4] or oleander, from its superficial resemblance to the unrelated olive Olea.[Note 1] It is so widely cultivated that no precise region of origin has been identified, though southwest Asia has been suggested. The ancient city of Volubilis in Morocco may have taken its name from the Berber name alili or oualilt for the flower.[5] Oleander is one of the most poisonous commonly grown garden plants.
The origins of the taxonomic name Nerium oleander, first assigned by Linnaeus in 1753, are disputed.[6] The genus name Nerium is the Latinized form of the Ancient Greek name for the plant Nerion (νήριον), which is in turn derived from the Greek for water, 'neros' (νηρός), because of the natural habitat of the oleander along rivers and streams.

The word Oleander appears as far back as the first century AD, when the Greek physician Pedanius Dioscorides cited it as one of the terms used by the Romans for the plant.[7] Merriam-Webster believes the word is a Medieval Latin corruption of Late Latin names for the plant: arodandrum or lorandrum, or more plausibly rhododendron (another Ancient Greek name for the plant), with the addition of Olea because of the superficial resemblance to the olive tree (Olea europea).[8][9] Another theory posited is that Oleander is the Latinized form of a Greek compound noun: 'οllyo' (ὀλλύω), which means 'I kill', and the Greek noun for man, 'aner', genitive 'andros' (ἀνήρ, ἀνδρός).[10] This is because of the Oleander's toxicity to humans.

The etymological association of oleander with the bay laurel has continued into the modern day: in France the plant is known as "Laurier Rose",[11] while the Spanish term, "Adelfa", is the descendant of the original Ancient Greek name for both the bay laurel and the oleander, daphne, which subsequently passed into Arabic usage and thence to Spain.
Oleander grows to 2–6 m (6.6–19.7 ft) tall, with erect stems that splay outward as they mature; first-year stems have a glaucous bloom, while mature stems have a grayish bark. The leaves are in pairs or whorls of three, thick and leathery, dark-green, narrow lanceolate, 5–21 cm (2.0–8.3 in) long and 1–3.5 cm (0.39–1.38 in) broad, and with an entire margin filled with minute reticulate venation web typical of eudicots. Leaves are light green and very glossy when young, before maturing to a dull dark green/greenish gray. The flowers grow in clusters at the end of each branch; they are white, pink to red,[Note 2] 2.5–5 cm (0.98–1.97 in) diameter, with a deeply 5-lobed fringed corolla round the central corolla tube. They are often, but not always, sweet-scented.[Note 3] The fruit is a long narrow pair of follicles 5–23 cm (2.0–9.1 in) long, which splits open at maturity to release numerous downy seeds.
Nerium oleander is either native or naturalized to a broad area from Mauritania, Morocco, and Portugal eastward through the Mediterranean region and the Sahara (where it is only found sporadically), to the Arabian peninsula, southern Asia, and as far east as Yunnan in southern parts of China.[13][14][15][16] It typically occurs around stream beds in river valleys, where it can alternatively tolerate long seasons of drought and inundation from winter rains. Nerium oleander is planted in many subtropical and tropical areas of the world. On the East Coast of the US, it grows as far north as Virginia Beach, Virginia, while in California and Texas miles of oleander shrubs are planted on median strips.[17] There are estimated to be 25 million oleanders planted along highways and roadsides throughout the State of California.[18] Because of its durability, oleander was planted prolifically on Galveston Island in Texas after the disastrous Hurricane of 1900. They are so prolific that Galveston is known as the 'Oleander City'; an annual oleander festival is hosted every spring.[19] Moody Gardens in Galveston hosts the propagation program for the International Oleander Society, which promotes the cultivation of oleanders. New varieties are hybridized and grown on the Moody Gardens grounds, encompassing every named variety.[20]

Beyond the traditional Mediterranean and subtropical range of oleander, the plant can also be cultivated in mild oceanic climates with the appropriate precautions. It is grown without protection in southern England and can reach great sizes in London and to a lesser extent in Paris[21] due to the urban heat island effect.[22][23][24] This is also the case with North American cities in the Pacific Northwest like Portland,[25] Seattle, and Vancouver. Plants may suffer damage or die back in such marginal climates during severe winter cold, but will rebound from the roots.
Some invertebrates are known to be unaffected by oleander toxins, and feed on the plants. Caterpillars of the polka-dot wasp moth (Syntomeida epilais) feed specifically on oleanders and survive by eating only the pulp surrounding the leaf-veins, avoiding the fibers. Larvae of the common crow butterfly (Euploea core) and oleander hawk-moth (Daphnis nerii) also feed on oleanders, and they retain or modify toxins, making them unpalatable to potential predators such as birds, but not to other invertebrates such as spiders and wasps.[citation needed]

The flowers require insect visits to set seed, and seem to be pollinated through a deception mechanism. The showy corolla acts as a potent advertisement to attract pollinators from a distance, but the flowers are nectarless and offer no reward to their visitors. They therefore receive very few visits, as typical of many rewardless flower species.[26][27] Fears of honey contamination with toxic oleander nectar are therefore unsubstantiated.
Oleander is a vigorous grower in warm subtropical regions, where it is extensively used as an ornamental plant in parks, along roadsides and in private gardens. It is most commonly grown in its natural shrub form, but can be trained into a small tree with a single trunk.[28] Hardy versions like white, red and pink oleander will tolerate occasional light frost down to −10 °C (14 °F),[16] though the leaves may be damaged. The toxicity of oleander renders it deer-resistant and its large size makes for a good windbreak – as such it is frequently planted as a hedge along property lines and in agricultural settings. The plant is tolerant of poor soils, intense heat, salt spray, and sustained drought – although it will flower and grow more vigorously with regular water. Although it does not require pruning to thrive and bloom, oleander can become unruly with age and older branches tend to become gangly, with new growth emerging from the base. For this reason gardeners are advised to prune mature shrubs in the autumn to shape and induce lush new growth and flowering for the following spring.[29] Unless they wish to harvest the seeds, many gardeners choose to prune away the seedpods that form on spent flower clusters, which are a drain on energy.[29]

In Mediterranean climates oleanders can be expected to bloom from April through October, with the heaviest bloom usually occurring between May and June. Free-flowering varieties like 'Petite Salmon' or 'Mont Blanc' require no period of rest and can flower continuously throughout the year if the weather remains warm.

In cold winter climates, oleander is a popular summer potted plant readily available at most nurseries. They require frequent heavy watering and fertilizing as compared to being planted in the ground, but oleander is nonetheless an ideal flowering shrub for patios and other spaces with hot sunshine. During the winter they should be moved indoors, ideally into an unheated greenhouse or basement where they can be allowed to go dormant.[28] Once they are dormant they require little light and only occasional watering. Placing them in a space with central heating and poor air flow can make them susceptible to a wide variety of pests - aphids, mealybugs, Oleander scale, Whitefly and Spider mites.
Oleander flowers are showy, profuse, and often fragrant, which makes them very attractive in many contexts. Over 400 cultivars have been named, with several additional flower colors not found in wild plants having been selected, including yellow, peach and salmon. Many cultivars, like "Hawaii" or "Turner's Carnival", are multi-colored, with brilliant striped corollas.[31] The solid whites, reds and a variety of pinks are the most common. Double flowered cultivars like "Mrs Isadore Dyer" (deep pink), "Mathilde Ferrier" (yellow) or "Mont Blanc" (white) are enjoyed for their large, rose-like blooms and strong fragrance. There is also a variegated form, 'Variegata', featuring leaves striped in yellow and white.[29] Several dwarf cultivars have also been developed, offering a more compact form and size for small spaces. These include "Little Red", "Petite White", "Petite Pink" and "Petite Salmon", which grow to about 8 feet at maturity.
Drugs derived from N. oleander have been investigated as a treatment for cancer, but have failed to demonstrate clinical utility.[33][34] According to the American Cancer Society, the trials conducted so far have produced no evidence of benefit, while they did cause adverse side effects.
Oleander has historically been considered a poisonous plant because some of its compounds may exhibit toxicity, especially to animals, when consumed in large amounts. Among these compounds are oleandrin and oleandrigenin, known as cardiac glycosides, which are known to have a narrow therapeutic index and can be toxic when ingested.

Toxicity studies of animals administered oleander extract concluded that rodents and birds were observed to be relatively insensitive to oleander cardiac glycosides.[36] Other mammals, however, such as dogs and humans, are relatively sensitive to the effects of cardiac glycosides and the clinical manifestations of "glycoside intoxication".[36][37][38]

In reviewing oleander toxicity cases seen in-hospital, Lanford and Boor[39] concluded that, except for children who might be at greater risk, "the human mortality associated with oleander ingestion is generally very low, even in cases of moderate intentional consumption (suicide attempts)".[39] In 2000, a rare instance of death from oleander poisoning occurred when two toddlers adopted from a Siberian orphanage ate the leaves from a neighbor's shrub in El Segundo, California.[40] A spokesman for the Los Angeles County Coroner's office stated that it was the first instance of death connected to oleander in the county, and a toxicologist from the California Poison Control Center said it was the first instance of death he had seen recorded. Because oleander is extremely bitter, officials speculated that the toddlers had developed a condition caused by malnutrition, pica, which causes people to eat otherwise inedible material.
Ingestion of this plant can affect the gastrointestinal system, the heart, and the central nervous system. The gastrointestinal effects can consist of nausea and vomiting, excess salivation, abdominal pain, diarrhea that may contain blood, and especially in horses, colic.[15] Cardiac reactions consist of irregular heart rate, sometimes characterized by a racing heart at first that then slows to below normal further along in the reaction. Extremities may become pale and cold due to poor or irregular circulation. The effect on the central nervous system may show itself in symptoms such as drowsiness, tremors or shaking of the muscles, seizures, collapse, and even coma that can lead to death.[citation needed]

Oleander sap can cause skin irritations, severe eye inflammation and irritation, and allergic reactions characterized by dermatitis.
Poisoning and reactions to oleander plants are evident quickly, requiring immediate medical care in suspected or known poisonings of both humans and animals.[42] Induced vomiting and gastric lavage are protective measures to reduce absorption of the toxic compounds. Activated charcoal may also be administered to help absorb any remaining toxins.[15] Further medical attention may be required depending on the severity of the poisoning and symptoms. Temporary cardiac pacing will be required in many cases (usually for a few days) until the toxin is excreted.[citation needed]

Digoxin immune fab is the best way to cure an oleander poisoning if inducing vomiting has no or minimal success, although it is usually used only for life-threatening conditions due to side effects.[43]

Drying of plant materials does not eliminate the toxins. It is also hazardous for animals such as sheep, horses, cattle, and other grazing animals, with as little as 100 g being enough to kill an adult horse.[44] Plant clippings are especially dangerous to horses, as they are sweet. In July 2009, several horses were poisoned in this manner from the leaves of the plant.[45] Symptoms of a poisoned horse include severe diarrhea and abnormal heartbeat. There is a wide range of toxins and secondary compounds within oleander, and care should be taken around this plant due to its toxic nature. Different names for oleander are used around the world in different locations, so, when encountering a plant with this appearance, regardless of the name used for it, one should exercise great care and caution to avoid ingestion of any part of the plant, including its sap and dried leaves or twigs. The dried or fresh branches should not be used for spearing food, for preparing a cooking fire, or as a food skewer. Many of the oleander relatives, such as the desert rose (Adenium obesum) found in East Africa, have similar leaves and flowers and are equally toxic.
Nerium oleander has a history of cultivation going back millennia, especially amongst the great ancient civilizations of the Mediterranean Basin. Some scholars believe it to be the rhodon (rose), also called the 'Rose of Jericho', mentioned in apocryphal writings (Ecclesiasticus XXIV, 13)[54] dating back to between 450 and 180 BC.[55] This is because no form of the traditional rose occurs in the wild in Palestine, but pink-flowering Oleander is common throughout the region near lakes and along stream or river beds.[56]

The ancient Greeks had several names for the plant, including rhododaphne, nerion, rhododendron and rhodon.[57] Pliny confirmed that the Romans had no Latin word for the plant, but used the Greek terms instead.[48] Pedanius Dioscorides states in his 1st century AD pharmacopeia De Materia Medica that the Romans used the Greek rhododendron but also the Latin Oleander and Laurorosa. The Egyptians apparently called it scinphe, the North Africans rhodedaphane, and the Lucanians (a southern Italic people) icmane.[58] Both Pliny and Dioscorides stated that oleander was an effective antidote to venomous snake bites if mixed with Rue and drunk.

A 2014 article in the medical journal Perspectives in Biology and Medicine posited that oleander was the substance used to induce hallucinations in the Pythia, the female priestess of Apollo, also known as the Oracle of Delphi in Ancient Greece.[59] According to this theory, the symptoms of the Pythia's trances (enthusiasmos) correspond to either inhaling the smoke of or chewing small amounts of oleander leaves, often called by the generic term laurel in Ancient Greece, which led to confusion with the bay laurel that ancient authors cite.

In his book Enquiries into Plants of circa 300 BC, Theophrastus described (among plants that affect the mind) a shrub he called onotheras, which modern editors render oleander; "the root of onotheras [oleander] administered in wine", he alleges, "makes the temper gentler and more cheerful".

The plant has a leaf like that of the almond, but smaller, and the flower is red like a rose. The plant itself (which loves hilly country) forms a large bush; the root is red and large, and, if this is dried, it gives off a fragrance like wine.

In another mention, of "wild bay" (Daphne agria), Theophrastus appears to intend the same shrub.[60]

Oleander was a very popular ornamental shrub in Roman peristyle gardens; it is one of the flora most frequently depicted on murals in Pompeii and elsewhere in Italy. These murals include the famous garden scene from the House of Livia at Prima Porta outside Rome, and those from the House of the Wedding of Alexander and the Marine Venus in Pompeii.[61]

Carbonized fragments of oleander wood have been identified at the Villa Poppaea in Oplontis, likewise buried by the eruption of Vesuvius in A.D. 79.[10] They were found to have been planted in a decorative arrangement with citron trees (Citrus medica) alongside the villa's swimming pool.

Herbaria of oleander varieties are compiled and held at the Smithsonian Institute in Washington, D.C. and at Moody Gardens in Galveston, Texas.
A bacterial disease known as oleander leaf scorch has become an extremely serious threat to the shrub since it was first noticed in Palm Springs, California, in 1992.[62] The disease has since decimated hundreds of thousands of shrubs mainly in Southern California, but also on a smaller scale in Arizona, Nevada and Texas.[63][29] The culprit is a bacterium called Xylella fastidiosa, which is spread via insects (the glassy-winged sharpshooter primarily) which feed on the tissue of oleanders and spread the bacteria. This inhibits the circulation of water in the tissue of the plant, causing individual branches to die until the entire plant is consumed.

Symptoms of leaf scorch infection may be slow to manifest themselves, but it becomes evident when parts of otherwise healthy oleanders begin to yellow and wither, as if scorched by heat or fire. Die-back may cease during winter dormancy, but the disease flares up in summer heat while the shrub is actively growing, which allows the bacteria to spread through the xylem of the plant. As such it can be difficult to identify at first because gardeners may mistake the symptoms for those of drought stress or nutrient deficiency.[64] Pruning out affected parts can slow the progression of the disease but not eliminate it.[62] This malaise can continue for several years until the plant completely dies—there is no known cure.[18] The best method for preventing further spread of the disease is to prune infected oleanders to the ground immediately after the infection is noticed.

'''