Pyrus_calleryana_text = '''
Pyrus calleryana, or the Callery pear, is a species of pear tree native to China and Vietnam,[1] in the family Rosaceae. It is most commonly known for its cultivar 'Bradford', widely planted throughout the United States and increasingly regarded as an invasive species.[1]

Pyrus calleryana is deciduous, growing to 5 to 8 m (16 to 26 ft) tall,[2] often with a conical to rounded crown. The leaves are oval, 4 to 8 cm (1.6 to 3.1 in) long, glossy dark green above, on long pedicels that make them flash their slightly paler undersides in a breeze. The white, five-petaled flowers are about 2 to 2.5 cm (0.79 to 0.98 in) in diameter. They are produced abundantly in early spring, before the leaves expand fully.

The inedible fruits of the Callery pear are small (less than one cm in diameter), and hard, almost woody, until softened by frost, after which they are readily taken by birds, which disperse the seeds in their droppings. In summer, the shining foliage is dark green and very smooth, and in autumn the leaves commonly turn brilliant colors, ranging from yellow and orange to more commonly red, pink, purple, and bronze. However, since the color often develops very late in autumn, the leaves may be killed by a hard frost before full color can develop.

Callery pears are remarkably resistant to disease or fireblight though some cultivars such as 'Bradford' are particularly susceptible to storm damage and are regularly disfigured or even killed by strong winds, ice storms, heavy snow, or limb loss due to their naturally rapid growth rate. The 'Bradford' in particular is also known for its sickly sweet, often unpleasant smell during its flowering stage.[3]

The species is named after the Italian-French sinologue Joseph-Marie Callery (1810–1862) who sent specimens of the tree to Europe from China.[4][5] The tree has a distinct scent often compared to chlorine or semen.
Numerous cultivars of Callery pear are offered commercially, including 'Aristocrat', 'Autumn Blaze', 'Bradford', 'Capital', 'Chanticleer' (also known as 'Cleveland Select'), 'New Bradford', 'Redspire', and 'Whitehouse'.
The trees were introduced to the U.S. by the United States Department of Agriculture facility at Glendale, MD as ornamental landscape trees in the mid-1960s. They became popular with landscapers because they were inexpensive, transported well and grew quickly. Lady Bird Johnson promoted the tree in 1966 by planting one in downtown Washington, D.C.[6][7] The New York Times also promoted the tree saying, "Few trees possess every desired attribute, but the Bradford ornamental pear comes unusually to close to the ideal."[8]

In much of North America these cultivars, particularly 'Bradford', are widely planted as ornamental trees. The trees are tolerant of a variety of soil types, drainage levels, and soil acidity. Their crown shape varies from ovate to elliptical, but may become asymmetric from limb loss due to excessive and unstable growth rate. The initial symmetry of several cultivars leads to their attempted use in settings such as industrial parks, streets, shopping centers, and office parks. Their dense clusters of white blossoms are conspicuous in early spring, though their smell is commonly found unpleasant by many people.[3] At the latitude of Pittsburgh, Pennsylvania, the trees often remain green until mid-November,[citation needed] and in warm autumns, the colors are often bright, although in a cold year they may get frozen off before coloring. In the South, Callery pears tend to be among the more reliable coloring trees.
The Bradford pear and related cultivars of Pyrus calleryana are regarded as invasive species in many areas of eastern and mid-Western North America, outcompeting many native plants and trees.[1] In the northeastern United States, wild Callery pears sometimes form extensive, nearly pure stands in old fields, along roadsides, and in similar disturbed areas.

While various cultivars of the Callery pear are commonly planted for their ornamental value, their prolifically produced fruits are taken by birds, which disperse the seeds in their droppings. The various cultivars are generally themselves self-incompatible, unable to produce fertile seeds when self-pollinated, or cross-pollinated with another tree of the same cultivar. However, if different cultivars of Callery pears are grown in proximity (within insect-pollination distance, about 300 ft or 100 m),[1] they often produce fertile seeds that can sprout and establish wherever they are dispersed. This technique was successfully used in the Dana Gould Gardens near Los Angeles.[9] The resulting wild individuals, of various genetic backgrounds, can in turn interbreed, producing more viable seed and furthering expansion and dispersal of the wild stand of the species. These plants often differ from the selected cultivars in their irregular crown shape and (sometimes) presence of thorns.

Callery pear is reported as established outside cultivation in 152 counties in 25 states in the United States.[10] While these wild plants are sometimes called "Bradford pear" (for the 'Bradford' cultivar), they are actually wild-growing descendants of multiple genotypes of Pyrus calleryana, and hence more correctly referred to by the common (or scientific) name of the species itself.[1]

The Bradford pear in particular has become further regarded as a nuisance tree for its initially neat, dense upward growth, which made it desirable in cramped urban spaces. Without corrective selective pruning at an early stage these weak crotches result in a multitude of narrow, weak forks, very susceptible to storm damage. Because of this, and the resulting relatively short life span (typically less than 25 years), many groups have discouraged further planting of 'Bradford' and other similarly structurally deficient Callery pear cultivars (such other as 'Cleveland Select') in favor of increasing use of locally native ornamental tree species.
Pear wood (of any species) is among the finest-textured of all fruitwoods. It is prized for making woodwind instruments, and pear veneer is used in fine furniture.[12] Pear wood is also among those preferred for preparing woodcuts for printing, either end-grained for small works or side-grained for larger.[13]

Callery pear has been used as rootstock for grafting such pear cultivars as Comice, Bosc, or Seckel, and especially for Nashi. Pyrus calleryana was first introduced into the United States in 1909 and 1916, largely influenced by the dedicated research of Frank N. Meyer, plant explorer for the US Department of Agriculture, commonly known for the discovery of the Meyer Lemon, for agricultural experimentation, pre-dating recognition in the 1950s of the species' potential as an ornamental plant.
'''