Rubus_idaeus_text = '''
Rubus idaeus (raspberry, also called red raspberry or occasionally as European raspberry to distinguish it from other raspberries) is a red-fruited species of Rubus native to Europe and northern Asia and commonly cultivated in other temperate regions.
A closely related plant in North America, sometimes regarded as the variety Rubus idaeus var. strigosus, is more commonly treated as a distinct species, Rubus strigosus (American red raspberry), as is done here.[4] Red-fruited cultivated raspberries, even in North America, are generally Rubus idaeus or horticultural derivatives of hybrids of R. idaeus and R. strigosus; these plants are all addressed in the present article.
Plants of Rubus idaeus are generally perennials which bear biennial stems ("canes") from a perennial root system. In its first year, a new, unbranched stem ("primocane") grows vigorously to its full height of 1.5–2.5 m (5.0–8.3 feet), bearing large pinnately compound leaves with five or seven leaflets, but usually no flowers. In its second year (as a "floricane"), a stem does not grow taller, but produces several side shoots, which bear smaller leaves with three or five leaflets. The flowers are produced in late spring on short racemes on the tips of these side shoots, each flower about 1 cm (0.4 inches) diameter with five white petals. The fruit is red, edible, and sweet but tart-flavoured, produced in summer or early autumn; in botanical terminology, it is not a berry at all, but an aggregate fruit of numerous drupelets around a central core. In raspberries (various species of Rubus subgenus Idaeobatus), the drupelets separate from the core when picked, leaving a hollow fruit, whereas in blackberries and most other species of Rubus, the drupelets stay attached to the core.
As a wild plant, R. idaeus typically grows in forests, forming open stands under a tree canopy, and denser stands in clearings. In the south of its range (southern Europe and central Asia), it only occurs at high altitudes in mountains.[7] The species name idaeus refers to its occurrence on Mount Ida near Troy in northwest Turkey, where the ancient Greeks were most familiar with it.
The fruit of R. idaeus is an important food crop, though most modern commercial raspberry cultivars derive from hybrids between R. idaeus and R. strigosus.[8] The fruits of wild plants have a sweet taste and are very aromatic.
Red raspberries contains 31 μg/100 g of folate.[9] Red raspberries have antioxidant effects that play a minor role in the killing of stomach and colon cancer cells.[10][11]

Young roots of Rubus idaeus prevented kidney stone formation in a mouse model of hyperoxaluria.[12] Tiliroside from raspberry is a potent tyrosinase inhibitor and might be used as a skin-whitening agent and pigmentation medicine.[13]

Raspberry fruit may protect the liver.
Vitamin C and phenolics are present in red raspberries. Most notably, the anthocyanins cyanidin-3-sophoroside, cyanidin-3-(2(G)-glucosylrutinoside) and cyanidin-3-glucoside, the two ellagitannins sanguiin H-6 and lambertianin C are present together with trace levels of flavonols, ellagic acid and hydroxycinnamate.[15]

Polyphenolic compounds from raspberry seeds have antioxidant effects in vitro,[16][17] but have no proven antioxidant effect in humans.[18] Raspberry ketones are derived from various fruits and plants, not raspberries, and are marketed as having weight loss benefits.[19] There is no clinical evidence for this effect in humans.

'''